backend:
  name: git-gateway
  branch: main # або інша гілка, де зберігається контент
  

media_folder: "src/assets/images"  # Де зберігати зображення
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"  # Місце для зберігання постів
    create: true  # Дозволяє створювати нові пости
    format: "json"
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }  # Замість markdown використовується string для звичайного тексту


